### PR TITLE
Fix - scroll bug

### LINKED ISSUE #10: Bug - scroll on main page
x, y axis unkown scroll

### PR DESCRIPTION
**Pull request by ghost**
[ISSUE](https://github.com/Enhmunh-E/tuuri-project/issues/10)

## Context
body{
overflow: hidden;
}

## Pull request checklist

You can delete the ones you don't need from the checklist👇

_input 'x' between bracket to check the list. Delete this line._

### General

- [x] Commit message is descriptive
- [x] Make a single commit
- [ ] Folder structure & File names meets naming conventions
- [ ] Responsive (Mobile)
- [ ] According to design

### CODE REVIEW

File: components/Carousel.tsx [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+  };
+  // let myslider: any;
+  const [myslider, setSlider] = useState<Slider>();
+  const slide = (y: number) => {
+    console.log("y:", y);
+    y > 0 ? myslider?.slickNext() : myslider?.slickPrev();
+  };
+
+  useEffect(() => {
+    console.log("event listening...");
```
Comment (Enhmunh-E) [inline components/Carousel.tsx:29]: useLess console log on production ;-;

File: providers/MainProvider.tsx [hunk 2]
```diff
@@ -21,7 +21,7 @@ export const MainProvider: FC<MainProviderProps> = ({ children }) => {
   useEffect(() => {
     const timer = setTimeout(() => {
       setLoading(false);
-    }, 3000);
```
Comment (Enhmunh-E) [inline providers/MainProvider.tsx:24]: change it back to original :)

**Review by Enhmunh-E — APPROVED** [review]

File: components/Carousel.tsx (hunk 1 above)
Comment (Akiko643) [reply components/Carousel.tsx:29]: ++

**Review by Enhmunh-E — CHANGES_REQUESTED** [review]

**Review by Enhmunh-E — APPROVED** [review]
